import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../theme';

const { width, height } = Dimensions.get('window');

export const getStyles = (colors, isDark = false) => {
  const cardBg = isDark ? 'rgba(255, 255, 255, 0.07)' : colors.cardBackground;
  const cardBorder = isDark ? 'rgba(255, 255, 255, 0.15)' : colors.border;
  const textPri = isDark ? '#FFFFFF' : colors.textPrimary;
  const textSec = isDark ? 'rgba(255, 255, 255, 0.65)' : colors.textSecondary;
  const borderLt = isDark ? 'rgba(255, 255, 255, 0.08)' : colors.borderLight;

  return StyleSheet.create({
    safeArea: {
      flex: 1,
      backgroundColor: isDark ? '#070E1E' : colors.cardBackground,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: width * 0.04,
      paddingVertical: height * 0.014,
      backgroundColor: isDark ? 'transparent' : colors.cardBackground,
      borderBottomWidth: 1,
      borderBottomColor: borderLt,
    },
    headerLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    headerTitle: {
      fontSize: width * 0.077,
      color: colors.primary,
      textShadowColor: isDark ? 'rgba(0, 0, 0, 0.85)' : 'rgba(11, 34, 64, 0.22)',
      textShadowOffset: { width: 1.2, height: 1.8 },
      textShadowRadius: 1.5,
      letterSpacing: 0.5,
    },
    bellButton: {
      width: width * 0.1,
      height: width * 0.1,
      borderRadius: (width * 0.1) / 2, // Fully circular button
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.08)' : colors.primaryLight, // Soft modern backdrop
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.15)' : 'rgba(11, 34, 64, 0.12)', // Sleek border highlight
      shadowColor: isDark ? '#000000' : colors.primaryDark,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: isDark ? 0.45 : 0.15,
      shadowRadius: 6,
      elevation: 4,
    },
    bellBadge: {
      position: 'absolute',
      top: width * 0.022,
      right: width * 0.022,
      width: width * 0.02,
      height: width * 0.02,
      borderRadius: (width * 0.02) / 2,
      backgroundColor: colors.error,
      borderWidth: 1,
      borderColor: isDark ? '#070E1E' : colors.cardBackground,
    },
    gradientBanner: {
      borderRadius: width * 0.05,
      width: width,
      alignSelf: 'center',
      marginTop: height * 0.02,
      overflow: 'hidden',
    },
    welcomeText: {
      fontSize: width * 0.061,
      color: colors.white,
      marginBottom: height * 0.02,
    },
    parentCard: {
      borderRadius: width * 0.05,
      padding: width * 0.04,
      flexDirection: 'row',
      alignItems: 'center',

      alignSelf: "flex-end",
      marginRight: width * 0.05,
      shadowOffset: { width: 0, height: height * 0.005 },
      shadowOpacity: 0.05,
      shadowRadius: width * 0.02,
      elevation: 3,
    },
    parentCardLeft: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    kidAvatar: {
      width: width * 0.125,
      height: width * 0.125,
      borderRadius: (width * 0.125) / 2,
    },
    kidInfo: {
      marginLeft: width * 0.035,
    },
    kidName: {
      fontSize: width * 0.04,
      color: textPri,
    },
    kidStatus: {
      fontSize: width * 0.0325,
      color: textSec,
      marginTop: height * 0.005,
    },
    sectionHeading: {
      fontSize: width * 0.045,
      color: textPri,
      marginHorizontal: width * 0.05,
      marginTop: height * 0.03,
      marginBottom: height * 0.0175,
    },
    activityContainer: {
      paddingHorizontal: width * 0.05,
    },
    timelineRow: {
      flexDirection: 'row',
    },
    timelineLeftColumn: {
      width: width * 0.05,
      alignItems: 'center',
    },
    timelineDot: {
      width: width * 0.025,
      height: width * 0.025,
      borderRadius: (width * 0.025) / 2,
      marginTop: height * 0.0275,
      zIndex: 2,
    },
    timelineLine: {
      width: 2,
      flex: 1,
      backgroundColor: cardBorder,
      marginTop: height * 0.005,
    },
    activityCard: {
      flex: 1,
      backgroundColor: cardBg,
      borderRadius: width * 0.04,
      padding: width * 0.04,
      marginLeft: width * 0.035,
      marginBottom: height * 0.0175,
      borderWidth: isDark ? 1.2 : 0,
      borderColor: cardBorder,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: height * 0.005 },
      shadowOpacity: 0.03,
      shadowRadius: width * 0.02,
      elevation: 2,
    },
    activityCardHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    activityTitle: {
      fontSize: width * 0.0375,
      color: textPri,
    },
    activityTime: {
      fontSize: width * 0.03,
      color: colors.primary,
    },
    activitySubtext: {
      fontSize: width * 0.0325,
      color: textSec,
      marginTop: height * 0.005,
    },
    fab: {
      position: 'absolute',
      bottom: height * 0.03,
      right: width * 0.05,
      width: width * 0.15,
      height: width * 0.15,
      borderRadius: (width * 0.15) / 2,
      backgroundColor: isDark ? '#1E293B' : colors.cardBackground,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: height * 0.005 },
      shadowOpacity: 0.15,
      shadowRadius: width * 0.025,
      elevation: 6,
      zIndex: 999,
      borderWidth: 1.5,
      borderColor: cardBorder,
      overflow: 'hidden',
    },
    fabIconImage: {
      width: '90%',
      height: '90%',
      marginTop: 2,
    },

    /* Inline Styles Cleaned up to Stylesheet */
    welcomePadding: {
      paddingHorizontal: width * 0.0375,
      paddingTop: height * 0.02,
    },
    childTransitCard: {
      marginTop: height * 0.025,
      width: width * 0.9,
      alignSelf: 'center',
      backgroundColor: cardBg,
      borderRadius: width * 0.06,
      overflow: 'hidden',
      borderWidth: 1.2,
      borderColor: cardBorder,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: height * 0.0125 },
      shadowOpacity: 0.06,
      shadowRadius: width * 0.05,
      elevation: 6,
    },
    mapContainer: {
      width: width * 0.9,
      height: height * 0.22,
      borderTopLeftRadius: width * 0.06,
      borderTopRightRadius: width * 0.06,
      overflow: 'hidden',
      position: 'relative',
    },
    map: {
      width: width * 0.9,
      height: height * 0.22,
    },
    routeBadgeOverlay: {
      position: 'absolute',
      bottom: height * 0.015,
      alignSelf: 'center',
      backgroundColor: isDark ? 'rgba(30, 41, 59, 0.9)' : 'rgba(255, 255, 255, 0.9)',
      paddingHorizontal: width * 0.035,
      paddingVertical: height * 0.0075,
      borderRadius: width * 0.05,
      borderWidth: isDark ? 1 : 0,
      borderColor: 'rgba(255, 255, 255, 0.12)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    liveBadge: {
      position: 'absolute',
      top: height * 0.02,
      right: width * 0.04,
      backgroundColor: colors.errorTranslucent,
      paddingHorizontal: width * 0.025,
      paddingVertical: height * 0.006,
      borderRadius: width * 0.03,
      flexDirection: 'row',
      alignItems: 'center',
    },
    liveDot: {
      width: width * 0.015,
      height: width * 0.015,
      borderRadius: (width * 0.015) / 2,
      backgroundColor: colors.white,
      marginRight: width * 0.015,
    },
    liveText: {
      color: colors.white,
      fontSize: width * 0.0275,
      fontWeight: '700',
      letterSpacing: 0.5,
    },
    pulseRingOuter: {
      position: 'absolute',
      width: width * 0.125,
      height: width * 0.125,
      borderRadius: (width * 0.125) / 2,
      backgroundColor: 'rgba(35, 120, 255, 0.25)',
      borderWidth: 1,
      borderColor: 'rgba(35, 120, 255, 0.4)',
    },
    pulseBusIcon: {
      width: width * 0.06,
      height: width * 0.06,
      borderRadius: (width * 0.06) / 2,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 2,
      borderColor: colors.white,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    routeBadge: {
      marginTop: height * 0.015,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.1)' : colors.cardBackground,
      paddingHorizontal: width * 0.035,
      paddingVertical: height * 0.0075,
      borderRadius: width * 0.05,
      borderWidth: isDark ? 1 : 0,
      borderColor: 'rgba(255, 255, 255, 0.12)',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    routeText: {
      color: isDark ? '#FFFFFF' : colors.primary,
      fontSize: width * 0.0325,
    },
    studentInfoContainer: {
      padding: width * 0.05,
    },
    rowSpaceBetween: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    rowAlignCenter: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    studentAvatar: {
      width: width * 0.13,
      height: width * 0.13,
      borderRadius: width * 0.04,
      marginRight: width * 0.035,
    },
    studentName: {
      fontSize: width * 0.0425,
      color: textPri,
    },
    studentGrade: {
      marginTop: height * 0.004,
      color: textSec,
      fontSize: width * 0.0325,
    },
    statusRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: height * 0.0075,
    },
    statusDotTransit: {
      width: width * 0.02,
      height: width * 0.02,
      borderRadius: (width * 0.02) / 2,
      backgroundColor: colors.primary,
      marginRight: width * 0.015,
    },
    statusTextTransit: {
      color: colors.primary,
      fontSize: width * 0.0325,
    },
    callDriverBtn: {
      width: width * 0.11,
      height: width * 0.11,
      borderRadius: (width * 0.11) / 2,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.06)' : colors.primaryLight,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: isDark ? 1.2 : 0,
      borderColor: cardBorder,
    },
    childHomeCard: {
      marginTop: height * 0.02,
      width: width * 0.9,
      alignSelf: 'center',
      backgroundColor: cardBg,
      borderRadius: width * 0.06,
      padding: width * 0.05,
      borderWidth: 1.2,
      borderColor: cardBorder,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: height * 0.0125 },
      shadowOpacity: 0.06,
      shadowRadius: width * 0.05,
      elevation: 6,
      marginBottom: height * 0.025,
    },
    homeBadgeOverlay: {
      position: 'absolute',
      bottom: -height * 0.0025,
      right: width * 0.03,
      backgroundColor: colors.success,
      width: width * 0.045,
      height: width * 0.045,
      borderRadius: (width * 0.045) / 2,
      justifyContent: 'center',
      alignItems: 'center',
      borderWidth: 1.5,
      borderColor: colors.white,
    },
    statusDotHome: {
      width: width * 0.02,
      height: width * 0.02,
      borderRadius: (width * 0.02) / 2,
      backgroundColor: colors.success,
      marginRight: width * 0.015,
    },
    statusTextHome: {
      color: colors.success,
      fontSize: width * 0.0325,
    },
    checkBadgeHome: {
      width: width * 0.11,
      height: width * 0.11,
      borderRadius: (width * 0.11) / 2,
      backgroundColor: colors.successLight,
      justifyContent: 'center',
      alignItems: 'center',
    },
    divider: {
      height: 1,
      backgroundColor: borderLt,
      marginVertical: height * 0.0175,
    },
    subStatusRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    subStatusText: {
      fontSize: width * 0.03,
      color: textSec,
    },
    chatBubbleContainer: {
      position: 'absolute',
      bottom: height * 0.03 + width * 0.15 + 12,
      right: width * 0.05,
      width: width * 0.72,
      zIndex: 1000,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.12,
      shadowRadius: 16,
      elevation: 8,
    },
    chatBubbleContent: {
      backgroundColor: isDark ? '#0F172A' : colors.cardBackground,
      borderRadius: width * 0.04,
      padding: width * 0.04,
      borderWidth: 1.5,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.12)' : colors.borderLightBlue,
      width: '100%',
    },
    chatBubbleHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: height * 0.006,
    },
    chatBubbleTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    chatBubbleBotIcon: {
      width: width * 0.055,
      height: width * 0.055,
      marginRight: width * 0.015,
    },
    chatBubbleBotName: {
      fontSize: width * 0.032,
      fontWeight: '700',
      color: textPri,
    },
    chatBubbleOnlineDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.success,
      marginLeft: 6,
    },
    chatBubbleText: {
      fontSize: width * 0.035,
      color: textSec,
      lineHeight: width * 0.048,
      marginTop: height * 0.004,
      fontWeight: '500',
    },
    chatBubbleButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary,
      alignSelf: 'flex-start',
      marginTop: height * 0.012,
      paddingVertical: height * 0.006,
      paddingHorizontal: width * 0.035,
      borderRadius: 15,
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
      elevation: 3,
    },
    chatBubbleButtonText: {
      fontSize: width * 0.028,
      color: colors.white,
      fontWeight: '700',
      marginRight: 2,
    },
    chatBubbleArrow: {
      position: 'absolute',
      bottom: -6,
      right: width * 0.075 - 6,
      width: 12,
      height: 12,
      backgroundColor: isDark ? '#0F172A' : colors.cardBackground,
      borderBottomWidth: 1.5,
      borderRightWidth: 1.5,
      borderColor: isDark ? 'rgba(255, 255, 255, 0.12)' : colors.borderLightBlue,
      transform: [{ rotate: '45deg' }],
      zIndex: 999,
    },
  });
};

export default getStyles(Colors);
