import { StyleSheet, Dimensions } from 'react-native';
import { Colors } from '../../theme';

const { width, height } = Dimensions.get('window');

export const getStyles = (colors) => {
  const isDark = colors.theme === 'dark';
  
  return StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.cardBackground,
      paddingHorizontal: width * 0.04,
      paddingVertical: height * 0.015,
      borderBottomWidth: 0.5,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.05,
      shadowRadius: 4,
      elevation: 3,
    },
    backButton: {
      width: width * 0.1,
      height: width * 0.1,
      borderRadius: (width * 0.1) / 2,
      backgroundColor: colors.background,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: width * 0.03,
    },
    headerTextContainer: {
      flex: 1,
    },
    headerTitle: {
      fontSize: width * 0.045,
      color: colors.textPrimary,
      fontFamily: 'Poppins-Bold',
    },
    contentList: {
      paddingVertical: height * 0.02,
      paddingHorizontal: width * 0.04,
    },
    childToggleContainer: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.cardBackground,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 12,
      marginBottom: height * 0.02,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    childToggleText: {
      fontSize: 12,
      color: colors.textSecondary,
      fontFamily: 'Poppins-Medium',
    },
    dropdownTrigger: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: isDark ? 'rgba(30, 41, 59, 0.8)' : '#EFF4FA',
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    dropdownTriggerText: {
      fontSize: 12,
      color: colors.textPrimary,
      fontFamily: 'Poppins-Bold',
      marginRight: 4,
    },
    dropdownMenu: {
      position: 'absolute',
      top: 36,
      right: 0,
      backgroundColor: isDark ? '#1E293B' : '#FFFFFF',
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: colors.border,
      paddingVertical: 4,
      width: 130,
      zIndex: 50,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.12,
      shadowRadius: 6,
      elevation: 5,
    },
    dropdownItem: {
      paddingVertical: 8,
      paddingHorizontal: 12,
    },
    dropdownItemBorder: {
      borderTopWidth: 0.5,
      borderTopColor: colors.border,
    },
    dropdownItemText: {
      fontSize: 12,
      fontFamily: 'Poppins-Regular',
    },
    sectionCard: {
      backgroundColor: colors.cardBackground,
      borderRadius: 20,
      padding: 18,
      marginBottom: height * 0.02,
      borderWidth: 0.5,
      borderColor: colors.border,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.04,
      shadowRadius: 8,
      elevation: 3,
    },
    sectionTitle: {
      fontSize: 14,
      color: colors.textPrimary,
      fontFamily: 'Poppins-Bold',
      lineHeight: 18,
      marginBottom: 4,
    },
    sectionSubtitle: {
      fontSize: 10,
      color: colors.textSecondary,
      fontFamily: 'Poppins-Regular',
      marginBottom: 16,
    },
    toggleRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    toggleRowLast: {
      borderBottomWidth: 0,
      paddingBottom: 4,
    },
    toggleLabelContainer: {
      flex: 1,
      marginRight: 16,
    },
    toggleLabel: {
      fontSize: 12,
      color: colors.textPrimary,
      fontFamily: 'Poppins-Bold',
    },
    toggleDescription: {
      fontSize: 9.5,
      color: colors.textSecondarySlate,
      fontFamily: 'Poppins-Regular',
      marginTop: 2,
    },
    inputContainer: {
      marginBottom: 14,
    },
    inputLabel: {
      fontSize: 10,
      color: colors.textSecondary,
      fontFamily: 'Poppins-Medium',
      marginBottom: 6,
    },
    textInput: {
      height: 44,
      borderRadius: 12,
      backgroundColor: colors.background,
      borderWidth: 0.5,
      borderColor: colors.border,
      paddingHorizontal: 12,
      fontSize: 12,
      color: colors.textPrimary,
      fontFamily: 'Poppins-Medium',
    },
    sliderRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      backgroundColor: colors.background,
      paddingHorizontal: 12,
      paddingVertical: 10,
      borderRadius: 12,
      borderWidth: 0.5,
      borderColor: colors.border,
      marginBottom: 18,
    },
    sliderLabel: {
      fontSize: 11,
      color: colors.textSecondary,
      fontFamily: 'Poppins-Medium',
    },
    sliderValue: {
      fontSize: 11,
      color: colors.primary,
      fontFamily: 'Poppins-Bold',
    },
    actionBtn: {
      height: 44,
      borderRadius: 12,
      backgroundColor: colors.primary,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 3 },
      shadowOpacity: 0.15,
      shadowRadius: 6,
      elevation: 3,
    },
    actionBtnText: {
      color: '#FFFFFF',
      fontSize: 12,
      fontFamily: 'Poppins-Bold',
    },
    geofenceItem: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 0.5,
      borderBottomColor: colors.border,
    },
    geofenceItemLast: {
      borderBottomWidth: 0,
      paddingBottom: 4,
    },
    geofenceIconContainer: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: colors.backgroundLight,
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    geofenceDetails: {
      flex: 1,
    },
    geofenceTitle: {
      fontSize: 12,
      color: colors.textPrimary,
      fontFamily: 'Poppins-Bold',
    },
    geofenceSub: {
      fontSize: 9.5,
      color: colors.textSecondarySlate,
      fontFamily: 'Poppins-Regular',
      marginTop: 2,
    },
    deleteBtn: {
      padding: 8,
    },
  });
};

export default getStyles(Colors);
